[package]
name = "nbtworkbench"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
strip = true
debug = false
lto = "fat"
panic = "abort"

[profile.release.build-override]
opt-level = 3
strip = true
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.bench]
inherits = "release"
strip = false
debug = true

[profile.bench.build-override]
inherits = "release"
strip = false
debug = true

[build-dependencies]
zune-png = "0.2.1"

[dependencies]
flate2 = "1.0.24"
winit = "0.28.6"
wgpu = "0.17.0"
pollster = "0.3.0"
cli-clipboard = "0.4.0"
indexmap = "2.0.0"
fxhash = "0.2.1"
num-traits = "0.2.16"
