[package]
name = "nbtworkbench"
version = "0.1.5"
edition = "2021"
description = "A modern NBT Editor written in rust. Optimized beyond belief"
license-file = "LICENSE"
repository = "https://github.com/RealRTTV/nbtworkbench"
readme = "README.md"
keywords = ["nbt", "window", "unsafe"]
categories = ["nbt"] # idk

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# for no_panic tests
[profile.nopanic]
inherits = "release"
panic = "unwind"

[profile.nopanic.build-override]
inherits = "release"

[profile.release]
opt-level = 3
codegen-units = 1
strip = true
debug = false
lto = "fat"
panic = "abort"

[profile.release.build-override]
opt-level = 3
strip = true
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.flame]
inherits = "release"
lto = "fat"
strip = false
debug = true

[profile.flame.build-override]
inherits = "release"
strip = false
debug = true

[build-dependencies]
zune-png = "0.2.1"
winres = "0.1.12"
flate2 = "1.0.27"

[dependencies]
zune-inflate = { version = "0.2.54", features = ["gzip", "zlib"] }
flate2 = "1.0.26"
winit = "0.28.6"
wgpu = "0.17.0"
pollster = "0.3.0"
cli-clipboard = "0.4.0"
fxhash = "0.2.1"
no-panic = "0.1.26"
hashbrown = { version = "0.14.0", features = ["raw"] }
fs2 = "0.4.3"
