[package]
name = "nbtworkbench"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release] # grab a cup of coffee, this'll take a bit
codegen-units = 1
strip = true
lto = true
panic = "abort"

[profile.release.build-override]
opt-level = 3
strip = true
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 1

[dependencies]
flate2 = "1.0.24"
winit = "0.27.1"
wgpu = "0.13.1"
pollster = "0.2"
unicode-segmentation = "1.10.0"
