[package]
name = "nbtworkbench"
version = "1.0.0"
edition = "2021"
description = "A modern NBT Editor written in Rust designed for performance and efficiency."
license-file = "LICENSE"
repository = "https://github.com/RealRTTV/nbtworkbench"
readme = "README.md"
keywords = ["nbt", "window", "unsafe", "editor", "tree"]
categories = ["graphics", "rendering", "text-editors", "parser-implementations"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
codegen-units = 1
strip = true
debug = false
lto = "fat"
panic = "abort"

[profile.release.build-override]
opt-level = 3
strip = true
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1

[profile.flame]
inherits = "release"
strip = false
debug = true

[profile.flame.build-override]
inherits = "release"
strip = false
debug = true

[build-dependencies]
zune-png = "0.4.10"
winres = "0.1.12"
flate2 = "1.0.27"

[dependencies]
zune-inflate = { version = "0.2.54", features = ["gzip", "zlib"] }
flate2 = "1.0.27"
winit = "0.29.10"
wgpu = "0.19.1"
pollster = "0.3.0"
cli-clipboard = "0.4.0"
fxhash = "0.2.1"
hashbrown = { version = "0.14.0", features = ["raw"] }
notify = "6.0.1"
uuid = { version = "1.4.1", features = ["v4"] }
compact_str = "0.7.1"
wgsl-inline = "0.2.0"
static_assertions = "1.1.0"
anyhow = "1.0.79"
