on:
    release:
      types: [created]

permissions:
    contents: write

jobs:
    release:
      name: release ${{ matrix.target }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          include:
            - target: x86_64-pc-windows-gnu
            - target: x86_64-unknown-linux-musl
            - target: x86_64-apple-darwin
            - target: wasm32-wasi
      steps:
        - uses: actions/checkout@master
        - name: Compile and release
          uses: rust-build/rust-build.action@v1.4.5
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            RUSTTARGET: ${{ matrix.target }}
            TOOLCHAIN_VERSION: nightly
        - uses: actions/upload-artifact@v4
          with:
            name: Executables
            path: target/${{ matrix.target }}/release/nbtworkbench.*
            if-no-files-found: error
            retention-days: 90
            compression-level: 9
