# kind of stolen from rustfmt

name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: disable git eol translation
        run: git config --global core.autocrlf false
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
          del rustup-init.exe
          rustup target add x86_64-pc-windows-gnu --toolchain nightly
        shell: powershell

      - name: Build and Test
        shell: cmd
        run: cargo +nightly build --release --target x86_64-pc-windows-gnu -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
