# kind of stolen from rustfmt

name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: disable git eol translation
        run: git config --global core.autocrlf false
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=nightly
          del rustup-init.exe
          rustup target add x86_64-pc-windows-msvc --toolchain nightly
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
        shell: powershell

      - name: Add mingw64 to path for x86_64-msvc
        shell: bash
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Build
        shell: cmd
        run: |
          cargo +nightly build --release --target x86_64-pc-windows-msvc -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
          tree /f

      - uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: target/x86_64-pc-windows-msvc/release/nbtworkbench.exe
          if-no-files-found: error
          retention-days: 90
          compression-level: 9
